name: BustaMine
version: ${version}
main: me.sat7.bustamine.BustaMine
depend:
  - Vault
softdepend:
  - EconomyPlus
api-version: 1.13
authors: [ MrXiaoM, sat7 ]
commands:
  BustaMine:
    description: "BustaMine"
    usage: /bm <money | exp | stats | top | go | stop | statistics | reloadConfig | reloadLang>
    aliases: [ bm, busta ]
